import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("io.github.goooler.shadow") version "8.1.8"
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        url = uri("https://mvn.lumine.io/repository/maven-public/")
    }
    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven {
        url = uri("https://repo.triumphteam.dev/snapshots/")
    }

}

dependencies {
    compileOnly("io.lumine:Mythic-Dist:5.6.1")
    implementation("com.github.stefvanschie.inventoryframework:IF:0.10.17")
    compileOnly("org.projectlombok:lombok:1.18.34")
    annotationProcessor("org.projectlombok:lombok:1.18.34")
    testCompileOnly("org.projectlombok:lombok:1.18.34")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.34")
    implementation("dev.triumphteam:triumph-cmd-bukkit:2.0.0-SNAPSHOT")
    implementation("org.projectlombok:lombok:1.18.22")
    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
}

group = "RLoots"
version = "1.0-SNAPSHOT"
description = "RLoots"
java.sourceCompatibility = JavaVersion.VERSION_21


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
tasks.withType<ShadowJar> {
    relocate("com.github.stefvanschie.inventoryframework", "me.taylan.inventoryframework")
    relocate("dev.triumphteam.cmd", "me.taylan.cmd")
}